In [1]:
import torch

In [2]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [3]:
x = torch.zeros([2, 5])
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [6]:
y = torch.rand([2, 5])
print(y)

tensor([[0.6620, 0.6598, 0.4896, 0.7923, 0.5286],
        [0.4124, 0.1310, 0.6421, 0.6949, 0.9158]])


In [7]:
# reshape like numpy.reshape()
y.view([1, 10])

tensor([[0.6620, 0.6598, 0.4896, 0.7923, 0.5286, 0.4124, 0.1310, 0.6421, 0.6949,
         0.9158]])